In [1]:
import pandas as pd

In [2]:
df=pd.DataFrame({
    'a':[1.9999,2,3],
    'b':[1,2.66666,3],
    'c':[1,2,3]
})
df=round(df,3)
df

     a      b  c
0  2.0  1.000  1
1  2.0  2.667  2
2  3.0  3.000  3

In [3]:
df.mean(axis='columns') #media das linhas, usando as colunas
df.mean(axis='index') #media das colunas, usando as linhas

a    2.333333
b    2.222333
c    2.000000
dtype: float64

In [6]:
df.rename(
    columns={
        'a':"A",
        'b':'B',
        'c':'C'
    },
    inplace=True #altera df nela mesma, sem precisar por no começo "df="
)
df

     A      B  C
0  2.0  1.000  1
1  2.0  2.667  2
2  3.0  3.000  3

In [ ]:
#se acrescentar no anterior antes do inplace 
# ,
#    index={
#        0:'x'

In [ ]:
#df.iloc[linha,coluna] 
#df.iloc[1,:]==df.iloc[linha,coluna]  

#igual ao numpy
#df.all é and
#df.any é or