# Exercício:

## 01 – Obtenha os resultados e retorne o objeto e código em Python dos seguintes cálculos:
a) 2.0 + 3.0 / 5.0

b) (a + 10.2) - 5.0 * 2.0

c) a / b + 33.8

d) a / (b + c)

e) d * 2

In [2]:
a=2.0+3.0/5.0
print(f'a = {a}')

b=(a+10.2)-5.0*2.0
print(f'b = {b}')

c=a/b+33.8
print(f'c = {c}')

d=a/(b+c)
print(f'd = {d}')

e=d*2
print(f'e = {e}')

a = 2.6
b = 2.799999999999999
c = 34.72857142857143
d = 0.0692805481537876
e = 0.1385610963075752

## 02 – Obtenha os resultados e retorne o código do objeto em Python dos seguintes cálculos:
a) [2.0, 3.0, 5.0] + [10, 20, 30]

b) lista_a * 2

c) lista_a + lista_b

d) lista_a / (lista_b * lista_c)

In [3]:
lista_a=[2.0, 3.0, 5.0] + [10, 20, 30]
print(f'lista_a = {lista_a}')

lista_b = lista_a * 2
print(f'lista_b = {lista_b}')

lista_c = lista_a + lista_b
print(f'lista_c = {lista_c}')

lista_a = [2.0, 3.0, 5.0, 10, 20, 30]
lista_b = [2.0, 3.0, 5.0, 10, 20, 30, 2.0, 3.0, 5.0, 10, 20, 30]
lista_c = [2.0, 3.0, 5.0, 10, 20, 30, 2.0, 3.0, 5.0, 10, 20, 30, 2.0, 3.0, 5.0, 10, 20, 30]

In [4]:
try:
    lista_d = lista_a / (lista_b * lista_c) 
    print(f'lista_d = {lista_d}')
except Exception as erro:
    print(f"Erro inesperado: {erro}")
#este cálculo não é possível, pois não é possível multiplicar ou dividir listas entre si.
#como o python não olha elemento por elemento nas listas, ele tenta multiplicar ou dividir as listas como um todo, o que não é permitido.

Erro inesperado: can't multiply sequence by non-int of type 'list'

## 03 – Usando os objetos simples obtidos no exercício 01 (a, b, c, d, e), instancie uma  lista. Instancie também uma segunda lista contendo a raiz quadrada dos valores obtidos nos objetos simples. Instancie uma terceira lista, concatenando as duas primeiras. Recupere a última lista.

In [5]:
lista1=[a,b,c,d,e]
#(a.sqrt(), b.sqrt(), c.sqrt(), d.sqrt(), e.sqrt()) não é possível, pois o método sqrt() não se aplica a números do tipo float.
lista2=[a**0.5, b**0.5, c**0.5, d**0.5, e**0.5]
lista3=lista1+lista2
print(f'lista3 = {lista3}')

lista3 = [2.6, 2.799999999999999, 34.72857142857143, 0.0692805481537876, 0.1385610963075752, 1.61245154965971, 1.6733200530681507, 5.893095233285427, 0.263211983302029, 0.3722379565648501]

## 04 – Duplique os valores contidos na lista final obtida no exercício anterior e converta para um array numpy. Remodele (reshape) o array, para que contenha 5 linhas e 4 colunas. Recupere o array.

In [6]:
lista3+=lista3

In [7]:
import numpy as np

In [8]:
array3=np.array(lista3)
arr3=array3.reshape(5,4)
arr3

array([[ 2.6       ,  2.8       , 34.72857143,  0.06928055],
       [ 0.1385611 ,  1.61245155,  1.67332005,  5.89309523],
       [ 0.26321198,  0.37223796,  2.6       ,  2.8       ],
       [34.72857143,  0.06928055,  0.1385611 ,  1.61245155],
       [ 1.67332005,  5.89309523,  0.26321198,  0.37223796]])

## 05 – Do array numpy obtenha uma lista contendo a média dos valores de cada uma das colunas.

In [9]:
lista_medias = arr3.mean(axis=0).tolist()
lista_medias

[7.8807329122498375, 2.1494130575327546, 7.8807329122498375, 2.149413057532755]

## 06 – Insira as médias das colunas no final do array do exercício 4.

**Contexto:**
- No exercício 4, você criou um array numpy com 5 linhas e 4 colunas (totalizando 20 valores)
- No exercício 5, você calculou a média de cada uma das 4 colunas (resultando em uma lista com 4 valores)

**Tarefa:**
1. Use o atributo `shape` do array do exercício 4 para calcular o número total de elementos.
2. Insira a lista de médias (do exercício 5) no final de outro array criado
3. Recupere e exiba o array resultante


Obs.:  Atributos não usam () na chamada.

In [10]:
arr3.shape

(5, 4)

In [11]:
array6=np.append(arr3,[lista_medias],axis=0)
array6

array([[ 2.6       ,  2.8       , 34.72857143,  0.06928055],
       [ 0.1385611 ,  1.61245155,  1.67332005,  5.89309523],
       [ 0.26321198,  0.37223796,  2.6       ,  2.8       ],
       [34.72857143,  0.06928055,  0.1385611 ,  1.61245155],
       [ 1.67332005,  5.89309523,  0.26321198,  0.37223796],
       [ 7.88073291,  2.14941306,  7.88073291,  2.14941306]])

## 07 – Remodele (reshape) o array do exercício anterior, para que contenha 4 colunas. Converta este objeto da classe array para DataFrame. Arredonde todos os valores para até 3 casas decimais. Recupere a DataFrame.

In [15]:
#O array do exercício anterior ja tem quatro colunas, mas o código seria o seguinte:
array6=array6.reshape(-1,4)
array6

array([[ 2.6       ,  2.8       , 34.72857143,  0.06928055],
       [ 0.1385611 ,  1.61245155,  1.67332005,  5.89309523],
       [ 0.26321198,  0.37223796,  2.6       ,  2.8       ],
       [34.72857143,  0.06928055,  0.1385611 ,  1.61245155],
       [ 1.67332005,  5.89309523,  0.26321198,  0.37223796],
       [ 7.88073291,  2.14941306,  7.88073291,  2.14941306]])

In [ ]:
import pandas as pd

In [ ]:
#convertendo o array para um DataFrame do pandas
df=pd.DataFrame(array6).round(3)
df

        0      1       2      3
0   2.600  2.800  34.729  0.069
1   0.139  1.612   1.673  5.893
2   0.263  0.372   2.600  2.800
3  34.729  0.069   0.139  1.612
4   1.673  5.893   0.263  0.372
5   7.881  2.149   7.881  2.149

## 08 – A última instancia desta DataFrame deve conter as médias dos valores contidos por coluna, o que foi determinado nos exercícios anteriores. Instancie um objeto contendo as médias dos valores em cada linha. Insira este objeto como uma nova coluna na DataFrame. Recupere a DataFrame.

In [ ]:
medias=df.mean(axis=1)
df[4] = medias
df

        0      1       2      3         4
0   2.600  2.800  34.729  0.069  10.04950
1   0.139  1.612   1.673  5.893   2.32925
2   0.263  0.372   2.600  2.800   1.50875
3  34.729  0.069   0.139  1.612   9.13725
4   1.673  5.893   0.263  0.372   2.05025
5   7.881  2.149   7.881  2.149   5.01500

## 09 – Usando o método dos objetos de classe DataFrame, describe(), compare os resultados contidos na última linha e última coluna da DataFrame.

Obs.: O método dos objetos de classe DataFrame, transpose(), inverte linhas por colunas.

In [ ]:
#resultado da média da última coluna, que tem a média de cada linha
df.describe().iloc[:,-1]

count     6.000000
mean      5.015000
std       3.758615
min       1.508750
25%       2.120000
50%       3.672125
75%       8.106688
max      10.049500
Name: 4, dtype: float64

In [ ]:
#resultado da média da última linha, que vem da lista das médias de cada coluna 
df.transpose().describe().iloc[:,-1]

count    5.000
mean     5.015
std      2.866
min      2.149
25%      2.149
50%      5.015
75%      7.881
max      7.881
Name: 5, dtype: float64

## 10 – Edite o nome das colunas e dos index, para indicar onde estão as médias. Qual a média das médias?

In [ ]:
df=df.rename(columns={4: "media_linhas"})
df=df.rename(index={5: "media_colunas"})
print(df)
df.mean().iloc[-1]
print(f'média das linhas: {df["media_linhas"].mean()}')
print(f'média das colunas: {df.loc["media_colunas"].mean()}')

                    0      1       2      3  media_linhas
0               2.600  2.800  34.729  0.069      10.04950
1               0.139  1.612   1.673  5.893       2.32925
2               0.263  0.372   2.600  2.800       1.50875
3              34.729  0.069   0.139  1.612       9.13725
4               1.673  5.893   0.263  0.372       2.05025
media_colunas   7.881  2.149   7.881  2.149       5.01500
média das linhas: 5.015000000000001
média das colunas: 5.015000000000001

In [ ]:
df.to_csv("df_10_lista7.csv")