# Exercício:

## 01 – Dados as operações abaixo, qual o resultado da operação lógica: 
p and q and r and s and t?
<br>
<br>Como os operadores lógicos podem ser usados para inverter o resultado?

<br>p = 2.0 + 3.0 / 5.0 == 10
<br>q = (p + 10.2) - 5.0 * 2.0 <= 2.9
<br>r = 10 <= p / q + 33.8 < 100
<br>s = 5 != p / (q + r)
<br>t = 33 == s * 2

In [1]:
p = 2.0 + 3.0 / 5.0 == 10 #F
q = (p + 10.2) - 5.0 * 2.0 <= 2.9 #T
r = 10 <= p / q + 33.8 < 100 #T
s = 5 != p / (q + r) #T
t = 33 == s * 2 #F

#da forma original, obtém-se falso em p and q and r and s and t
#para alterar para True:

p or q and r and s and not t

True

## 02 – Usando apenas o operador or, qual seria o resultado final das operações abaixo? Como deve ser usado o not para inverter o resultado?

<br>p = ('a',1,True,'b',0,False) != ('a',True,1,'b',False,0)
<br>q = ['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)
<br>r = ['a',1,True,'b',0,False] != ['a',True,1,'b',False,0]
<br>s = ['a',1,True,'b',0,False] > ['a',True,1]
<br>t = ['a',1,True,'b',0,False] == 1
<br>u = ['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False]

In [2]:
p = ('a',1,True,'b',0,False) != ('a',True,1,'b',False,0)
q = ['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)
r = ['a',1,True,'b',0,False] != ['a',True,1,'b',False,0]
s = ['a',1,True,'b',0,False] > ['a',True,1]
t = ['a',1,True,'b',0,False] == 1
u = ['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False]

p or q or r or s or t or u

True

In [3]:
#se p é false, q é true, r é false, s é true, t é false e u é true, então para obter false:

p or not q or r or not s or t or not u

False

## 03 – No exercício 3 da aula 8 foi importado um arquivo .csv para um objeto da classe DataFrame pandas. Importe aqui o mesmo objeto e arredonde e edite o index como realizado no exercício 3 da aula 8. Usando operadores responda, a segunda linha é igual a terceira ou a terceira linha é igual a quarta?

In [4]:
import pandas as pd

In [5]:
df8_3 = pd.read_csv("df_10_lista7.csv", index_col="Unnamed: 0").round(3)
comp1=(df8_3.iloc[1]==df8_3.iloc[2]).all()
comp2=(df8_3.iloc[2]==df8_3.iloc[3]).all()
print(comp1 or comp2)

False

## 04 – Usando operadores verifique se todos os valores contidos na primeira linha são maiores ou iguais a 10.

In [6]:
print((df8_3.iloc[0] >= 10).all())

False

## 05 – Usando operadores verifique se todos os valores contidos na terceira coluna estão entre 0 inclusive e 40.

In [7]:
print(((df8_3.iloc[:, 2] >= 0) & (df8_3.iloc[:, 2] < 40)).all())

True

## 06 – Usando operadores verifique se algum dos valores contidos na última linha está acima de 10.

In [8]:
print((df8_3.iloc[-1] > 10).any())

False

## 07 – Recupere a DataFrame contendo apenas valores que estejam acima de 5 e abaixo de 7.

In [9]:
df8_3[(df8_3 > 5) & (df8_3 < 7)]

                0      1   2      3  media_linhas
0             NaN    NaN NaN    NaN           NaN
1             NaN    NaN NaN  5.893           NaN
2             NaN    NaN NaN    NaN           NaN
3             NaN    NaN NaN    NaN           NaN
4             NaN  5.893 NaN    NaN           NaN
media_colunas NaN    NaN NaN    NaN         5.015

## 08 – Recupere a DataFrame contendo apenas valores que estejam abaixo de 5 inclusive ou acima de 7.

In [10]:
df8_3[(df8_3 <= 5) | (df8_3 > 7)]

                    0      1       2      3  media_linhas
0               2.600  2.800  34.729  0.069        10.050
1               0.139  1.612   1.673    NaN         2.329
2               0.263  0.372   2.600  2.800         1.509
3              34.729  0.069   0.139  1.612         9.137
4               1.673    NaN   0.263  0.372         2.050
media_colunas   7.881  2.149   7.881  2.149           NaN

## 09 – Converta as duas últimas colunas do objeto DataFrame para dois objetos da classe numpy array. Algum dos valores contidos no primeiro array estão entre 2 inclusive e 5 inclusive?

In [ ]:
import numpy as np

In [18]:
df8_3

                    0      1       2      3  media_linhas
0               2.600  2.800  34.729  0.069        10.050
1               0.139  1.612   1.673  5.893         2.329
2               0.263  0.372   2.600  2.800         1.509
3              34.729  0.069   0.139  1.612         9.137
4               1.673  5.893   0.263  0.372         2.050
media_colunas   7.881  2.149   7.881  2.149         5.015

In [26]:
arr_col4=np.array(df8_3.iloc[:,3])
arr_col5=np.array(df8_3.iloc[:,4])
print(((arr_col4>=2) & (arr_col4<=5)).any())

True

## 10 – Os valores contidos nos dois arrays são superiores à -1 e inferiores à 12?

In [32]:
print(((arr_col4>-1) & (arr_col4<12)).all() & 
      ((arr_col5>-1) & (arr_col5<12)).all())

True